import { PT_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import Layout from "@/Components/Layout";

const PTSerif = PT_Serif({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "  | Diyetisyen Yunus Aksu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PTSerif.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
